plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

javafx {
    version = '25'
    modules = ['javafx.controls']
}

application.mainClass = 'ca.kieve.ssss.editor.EditorApp'

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-headless:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
    implementation "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-desktop"
    implementation 'io.github.mkpaz:atlantafx-base:2.1.0'
}

run {
    workingDir = rootProject.file('assets').path
    jvmArgs += '--add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED'
}
